[[rule]]
formatting.align_entries = false
formatting.reorder_keys  = false
include                  = ["settings.toml"]
schema.enabled           = true
schema.path              = "settings-schema.json"
[formatting]
align_entries         = true
allowed_blank_lines   = 1
array_auto_collapse   = false
array_auto_expand     = false
array_trailing_comma  = true
column_width          = 100
compact_arrays        = true
compact_inline_tables = false
crlf                  = false
indent_entries        = false
indent_tables         = false
reorder_keys          = true
trailing_newline      = true
