[[rule]]
include = ["settings.toml"]
formatting.align_entries = true
schema.path = "settings-schema.json"
schema.enabled = true
[formatting]
align_entries = true
array_trailing_comma = true
array_auto_expand = false
array_auto_collapse = false
compact_arrays = false
compact_inline_tables = false
column_width = 100
indent_tables = false
indent_entries = false
trailing_newline = true
reorder_keys = true
allowed_blank_lines = 1
crlf = false
